### ISSUE TITLE
remove duplicates in the csv

### ISSUE THREAD

**Issue by chhongs** [chhongs/cloud-bug-prediction-asat#12]
The code produces multiple instances of the same class, sometimes indicating there is a bug sometimes not.
Happens because the metrics are computed for each commit and each affected file in the commit.

**Comment by chhongs** [comment]
Couldn't find a way to do this, yet.
Perhaps extend the ML pipeline to preprocess the data accordingly.

**Comment by YasaraPeiris** [comment]
Required functionalities have implemented in both java code level and machine learning preprocessing level.
